print('========= DESAFIO 05 =========')
num=input('Digite algo: ')
print('Tem número?')
print(num.isnumeric())
print('Tem letra?')
print(num.isalpha())
print('Tem número e letra?')
print(num.isalnum())
print('Está em maiúcula?')
print(num.isupper())
print('Está em minúscula?')
print(num.islower())
print('Tem espaço?')
print(num.isspace())
